<?php
/**
 * This is a system wide global configuration file for "p2pGestor" 
 *
 *
 * 
 *
 * Version 0.1  2016-08-02
 *
 * 
 *
 *
 */
// this is where all the php code files are stored that implement company specific
// functions and/or classes
$config['companySpecificPhpCodeBaseDir'] = APP. "companyCodeFiles" . DS;
$config['dataBaseBackupDir'] = APP. "DBbackups" . DS;
$config['dashboard2JobsInParallel'] = 1;
$config['investorFiles'] = APP. "files" . DS . "dashboard2" . DS;
$config['dashboard2Files'] = APP. "files" . DS . "dashboard2" . DS;
$config['winvestifyVendor'] = APP. "WinvestifyVendor" . DS;  
$config['vendor'] = APP. "Vendor" . DS;  
$config['winvestifyErrorFiles'] = APP . "files" . DS . "winvestifyErrors" . DS; // The directory where the files are stored when an error has 
                                                                                // been detected



/*
 * 	The number of companies whose marketplace portal is to be read during a cronjob sequence
 * 	Typical value 1
 *
 */
$config['numberOfSimultaneousMarketplaceRequests'] = 1;


// Configuration of the event which the system will deal with   0 = NO, 1 = YES
$config['event']['betaTesterCreated'] = 1;                                      // Somebody wants to become a Beta test. 
$config['event']['newUserCreated'] = 1;                                         // A new user has successfully registered
$config['event']['confirmationCodeGenerated'] = 1;                              // an SMS generated												
$config['event']['errorReported'] = 1;                                          // an error was reported by user 		
$config['event']['Model.Email.SendMessage'] = 1;                                // contact mailing 
$config['event']['checkMessage'] = 1;                                           // contact winadmin
$config['event']['pfpMail'] = 1;                                                // contact pfp
$config['event']['billMailEvent'] = 1;                                          // contact pfp
$config['event']['applicationErrorReported'] = 1;                               // Application error
$config['event']['errorApplication'] = 1;                                       // An error has occurred 
$config['event']['accountLinkingFullyFinished'] = 1;                            // The account linking and analysis has finished


// Administration configurations
$config['SMSadmin']['SMS_Originator'] = "Winvestify";                           // Name of originator of sent SMS's
//$config['SMSadmin']['AuthKey'] = "live_R53sCVZxcapbIDUfKFzjCorFx";            // Authentication Key for SMS platform, live key MOVED TO DATABASE
//$config['SMSadmin']['AuthKey'] = "test_rXD6WrG0pUiV4Q8quEUeRDbwJ"; 		// Authentication Key for SMS platform, key for testing  


// administration configurations OBSOLETE, SUPERSEEDED BY DEFINITIONS OF V2 OF CONTACT FORM
// These persons receive notifications
//$config['admin']['systemAdmin'] = "antoine@winvestify.com";
//$config['admin']['winAdminCheck'] = "antoine@winvestify.com";                 // admin who receives notification when a user has finished 1CR form
//$config['admin']['genericEmailOriginator'] = "no-reply@winvestify.com";       // All automated emails generated by the platform are sent from this user.


$config['DefinitionActiveUser'] = 10;                                           // A user is considered an active user if s/he enters at least
                                                                                // every x days in our portal


$config['CollectNewInvestmentData'] = 2;                                        // The frequency with which we will refresh the investment 																

$config['Tallyman']['maxHistoryLengthDays'] = 150;                              // The maximum historic data to be included, for displaying purposes in
                                                                                // Tallyman service in days
$config['Tallyman']['maxHistoryLengthNumber'] = 50;                             // The maximum historic data to be included, for displaying purposes in
                                                                                // Tallyman service in number of records
$config['Tallyman']['validBeforeExpiration'] = 7;                               // Valid period of a reading for Tallyman. Exceedig this
                                                                                // period a reading is considered as new and will be accounted
                                                                                // unit = days.
$config['Tallyman']['maxReadingsintoMldata'] = 12;                              // maximum records to process for storing data into mldata database
                                                                                // unit = number of database record
$config['backup']['limit'] = 1000;                                              // Limit in marketplaceback find, min = 1, max = ?.


$config['files']['investorPath'] = APP . 'files' . DS .'investors';             //Path to investor uploaded files
$config['files']['billsPath'] = APP . 'files' .DS . 'pfpCompanies' . DS . 'bills'; //Path to bills 
$config['files']['maxSize'] = 10000000;                                         // Max size 10MB       
$config['files']['permittedFilesShort'] = array(".png", ".gif", ".jpg", ".pdf");
$config['files']['permittedFiles'] = array("image/png", "image/gif", "image/jpeg", "application/pdf");


$config['backup']['limit'] = 1000;                                              // Limit in marketplaceback find, min = 1, max = 2000.

// $config['geolocationApi']['AuthKey'] = "40d49470983cedfb136010af6c2c9d4e";   MOVED TO DATABASE

//$config['winvestify']['version'] = '0.8.0';                                   MOVED TO DATABASE

// These persons receive notifications
$config['admin']['systemAdmin'] = "antoine@winvestify.com";
$config['admin']['customerCare'] = "ana@winvestify.com";
$config['admin']['winAdminCheck'] = "ana@winvestify.com";                       // admin who receives notification when a user has finished 1CR form

$config['admin']['genericEmailOriginator'] = "no-reply@winvestify.com";         // All automated emails generated by the platform are sent from this user.
$config['admin']['genericSMSOriginator'] = "Winvestify";                        // All SMS will originate from this "user"

// To add a new field to the subject dropdown:
// 1st Add the new option in the array 'subjectContactForm' with their translation
// 2nd Add in the array 'subjectEmailRecipient' with the email who will receive the email
$config['subjectContactForm'] = array(''=> ('Choose one...'),                   //***** NEED TRANSLATE
                            'general'       => ('General'),
                            'billing'       => ('Billing Dept'),                                      
                            'improvement'   => ('Functional Improvement'),
                            'feature'       => ('New Feature'), 
                            'requestaccess' => ('Request Access'),    
                            'unsubscribe'   => ('Unsubscribe Account'),
                            );
                            
$config['subjectEmailRecipient'] = array(array('choose', $config['admin']['systemAdmin']),
                                array('general', $config['admin']['systemAdmin']),
                                array('billing', $config['admin']['customerCare']), 
                                array('improvement', $config['admin']['systemAdmin']),
                                array('feature', $config['admin']['systemAdmin']), 
                                array('requestaccess', $config['admin']['customerCare']),    
                                array('unsubscribe', $config['admin']['customerCare'])
                                );

$config['flow2Filter'] = false;

$config['generateLink'] = array (
    'linkedaccounts'    => '1.0',
    'dashboards'        => '1.0',
    'pollingresources'  => '1.0', 
    'investors'         => '1.0',
    'emails'            => '1.0',
    'companies'         => '1.0',
    'globaldashboards'  => '1.0',
);