<?php
/**
 * This is a system wide global configuration file for "p2pGestor" 
 *
 *
 * 
 *
 * Version 0.1  2017-04-01
 *
 * 
 *
 *
 */

  
  
// this is where all the php code files are stored that implement company specific
// functions and/or classes
$config['companySpecificPhpCodeBaseDir'] = APP. "companyCodeFiles" . DS;
$config['dataBaseBackupDir'] = APP. "DBbackups" . DS;




/*
*	The number of companies whose marketplace portal is to be read during a cronjob sequence
*	Typical value 1
*
*/
$config['numberOfSimultaneousMarketplaceRequests'] = 1;






// Configuration of the event which the system will deal with   0 = NO, 1 = YES
$config['event']['betaTesterCreated']		 		= 1;        		// Somebody wants to become a Beta test. 
$config['event']['newUserCreated']			 	= 1;                    // A new user has successfully registered
$config['event']['confirmationCodeGenerated']			= 1;                    // an SMS generated												
$config['event']['errorReported']				= 1;                    // an error was reported by user 		
$config['event']['newSuggestion']				= 1;                    // a suggestion was generated by user
$config['event']['sendContactMessage']                          = 1;                    //contact form mailing

// Administration configurations
$config['SMSadmin']['SMS_Originator'] = "Winvestify"; 					// Name of originator of sent SMS's
$config['SMSadmin']['AuthKey'] = "live_R53sCVZxcapbIDUfKFzjCorFx";                      // Authentication Key for SMS platform, live key
//$config['SMSadmin']['AuthKey'] = "test_rXD6WrG0pUiV4Q8quEUeRDbwJ";                    // Authentication Key for SMS platform, key for testing  
// administration configurations

// these persons receive notifications
$config['admin']['systemAdmin'] = "antoine.azarus@gmail.com";
														

$config['admin']['genericEmailOriginator'] = "no-reply@winvestify.com";                 // All automated emails generated by the platform are sent from this user.



$config['DefinitionActiveUser'] = 10;							// A user is considered an active user if s/he enters at least
											// every x days in our portal

$config['CollectNewInvestmentData'] = 2;						// The frequency with which we will refresh the investment information																	
											// of the user, in units of hours