<?php
/*
 * +-----------------------------------------------------------------------+
 * | Copyright (C) 2016, http://beyond-language-skills.com                 |
 * +-----------------------------------------------------------------------+
 * | This file is free software; you can redistribute it and/or modify     |
 * | it under the terms of the GNU General Public License as published by  |
 * | the Free Software Foundation; either version 2 of the License, or     |
 * | (at your option) any later version.                                   |
 * | This file is distributed in the hope that it will be useful           |
 * | but WITHOUT ANY WARRANTY; without even the implied warranty of        |
 * | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          |
 * | GNU General Public License for more details.                          |
 * +-----------------------------------------------------------------------+
 * | Author: Antoine de Poorter                                            |
 * +-----------------------------------------------------------------------+
 *
 *
 * @author Antoine de Poorter
 * @version 0.1
 * @date 2016-08-02	
 * @package
 * 

  2016-08-02	  version 2016_0.1


  Pending


 */

//App::uses('CakeEvent', 'Event');
class CompanysController extends AppController {

    var $name = 'Companys';
    var $uses = array('Company');
    var $error;

    function beforeFilter() {
        parent::beforeFilter(); // only call if the generic code for all the classes is required.
    }

    /**
     *
     * 	Add a new company
     * 	
     */
    function v1_add() {


    }

    /**
     * Modify one or more data of a company
     * 	
     * @param int   $id The database identifier of the requested 'Company' resource
     */
    function v1_edit($id) {

	
    }

    /**
     * Deletes (make it "invisible" to normal admin) of a company
     * 	
     * @param int   $id The database identifier of the requested 'Company' resource
     */
    function v1_delete($id) {


    }


    /** 
     * 	Get all the data of a company
     * 	
     */
    function readCompanyListData() {

        $companyFilterConditions = array('id >' => 0); // read all companies
        $companyResult = getCompanyDataList($companyFilterConditions);
        $this->set('companyResult', $companyResult);
    }

    /**
     *  
     * 	Show "public" data of the companies, some provided by our own users, some 'mined' from
     * 	"public" sources and some generated by ourselves
     * 	The RATE button is only active for the companies where the user has a linked account (AND? an investment??)
     */
    function showCompanyDataPanel() {
        Configure::write('debug', 0);

        $user = $this->Auth->user();

        $companyFilterConditions = array('Company.id >' => 0);   // read all companies
        $companyResults = $this->Company->getCompanyDataList($companyFilterConditions);

        $this->set('companyResults', $companyResults);

    }

    /**
     * 	Provides extra data about a company
     *
     */
    function readCompanyExtendedData() {

        if (!$this->request->is('ajax')) {
            throw new
            FatalErrorException(__('You cannot access this page directly'));
        }

        $error = false;
        $this->layout = 'ajax';
        $this->disableCache();

        $companyId = $_REQUEST['companyId'];

        $companyExtendedDataResult = $this->Company->readExtendedData($companyId);

        $this->set('companyExtendedDataResult', $companyExtendedDataResult);
        $this->set('companyId', $companyId);
        $this->set('error', $error);
    }

    
    /** 
     * This methods terminates the HTTP GET.
     * Format GET /api/1.0/companies.json&_fields=x,y,z
     * Example GET /api/1.0/companies.json&company_country=ES,company_countryName=SPAIN&_fields=company_name,company_country,company_logoGUID
     * 
     * @param -
     * @return array $apiResult A list of elements of array "company"
     */
    public function v1_index(){       
        $this->checkAcl();
        if (empty($this->listOfFields)) {
            $this->listOfFields = ['id', 'company_name','company_url', 
                                    'company_country', 'company_countryName', 
                                    'company_privacyUrl', 'company_termsUrl',
                                    'company_logoGUID'
                                  ]; 
        } 

        $results = $this->Company->find("all", $params = ['conditions' => $this->listOfQueryParams,
                                                          'fields' => $this->listOfFields,
                                                          'recursive' => -1]);

        $j = 0;

        if (empty($results)) {
            $apiResult = ["data" => null];
        }
        else {
            foreach ($results as $resultItem) { 
                $this->Company->apiVariableNameOutAdapter( $resultItem['Company']);

                foreach ($resultItem['Company'] as $key => $value) {
                    $apiResult[$j][$key] = $value;  
                }
                $j++;
            }
        }
        $resultJson = json_encode($apiResult);
    
        $this->response->statusCode(200);
        $this->response->type('json');
        $this->response->body($resultJson); 

        return $this->response;          
    }
    
    /** 
     * This methods terminates the HTTP GET.
     * Format GET /api/1.0/companies/[companyId]&fields=x,y,z
     * Example GET /api/1.0/companies/1.json&_fields=company_name,company_countryName
     * 
     * @param int   $id The database identifier of the requested 'Company' resource
     * @return array $apiResult A list of field (variables) of array "company"
     */   
   public function v1_view(){

        $id = $this->request->id;
 /*          
        if (empty($this->listOfFields)) {
            $this->listOfFields = ['company_name','company_url', 
                                    'company_country', 'company_countryName', 
                                    'company_privacyUrl', 'company_termsUrl',
                                    'company_logoGUID'
                                  ]; 
        }  
*/
        $apiResult = $this->Company->find('first', $params= ['conditions' => ['id' => $id],
                                                          'fields' => $this->listOfFields, 
                                                          'recursive' => -1
                                                         ]);

        $this->Company->apiVariableNameOutAdapter($apiResult['Company']);
    
        $this->set(['data' => $apiResult['Company'],
                  '_serialize' => ['data']]
                   );      
    }    
    
    
    
}
